# Generated by Django 5.2.15 on 2026-09-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issue_optional_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftissue',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftissue',
            name='target_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
