# Generated by Django 5.2.15 on 2026-10-03 16:44

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0124_draft_optional_times"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCustomField",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_key", models.TextField(editable=False)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("number", "number"),
                            ("currency", "currency"),
                            ("date", "date"),
                            ("checkbox", "checkbox"),
                            ("select", "select"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "project_custom_fields",
                "ordering": ("sort_order", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProjectCustomFieldOption",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("color", models.CharField(default="#808080", max_length=7)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_retired", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="db.projectcustomfield",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "project_custom_field_options",
                "ordering": ("sort_order", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="IssueCustomFieldValue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("text_value", models.TextField(null=True)),
                (
                    "decimal_value",
                    models.DecimalField(decimal_places=6, max_digits=24, null=True),
                ),
                ("date_value", models.DateField(null=True)),
                ("boolean_value", models.BooleanField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="db.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_%(class)s",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_%(class)s",
                        to="db.workspace",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_values",
                        to="db.projectcustomfield",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="issue_values",
                        to="db.projectcustomfieldoption",
                    ),
                ),
            ],
            options={
                "db_table": "issue_custom_field_values",
            },
        ),
        migrations.AddIndex(
            model_name="projectcustomfield",
            index=models.Index(
                fields=["project", "is_archived", "sort_order"],
                name="cf_project_active_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcustomfield",
            constraint=models.UniqueConstraint(
                fields=("project", "name_key"), name="cf_project_name_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="projectcustomfieldoption",
            index=models.Index(
                fields=["field", "sort_order"], name="cf_option_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecustomfieldvalue",
            index=models.Index(
                models.F("field"),
                django.db.models.functions.text.Substr("text_value", 1, 600),
                name="cf_value_text_prefix_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuecustomfieldvalue",
            index=models.Index(
                fields=["field", "decimal_value"], name="cf_value_decimal_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecustomfieldvalue",
            index=models.Index(
                fields=["field", "date_value"], name="cf_value_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecustomfieldvalue",
            index=models.Index(
                fields=["field", "boolean_value"], name="cf_value_bool_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecustomfieldvalue",
            index=models.Index(fields=["field", "option"], name="cf_value_option_idx"),
        ),
        migrations.AddConstraint(
            model_name="issuecustomfieldvalue",
            constraint=models.UniqueConstraint(
                fields=("issue", "field"), name="cf_issue_field_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="issuecustomfieldvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", True),
                        ("decimal_value__isnull", True),
                        ("option__isnull", True),
                        ("text_value__isnull", False),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", True),
                        ("decimal_value__isnull", False),
                        ("option__isnull", True),
                        ("text_value__isnull", True),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", False),
                        ("decimal_value__isnull", True),
                        ("option__isnull", True),
                        ("text_value__isnull", True),
                    ),
                    models.Q(
                        ("boolean_value__isnull", False),
                        ("date_value__isnull", True),
                        ("decimal_value__isnull", True),
                        ("option__isnull", True),
                        ("text_value__isnull", True),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("date_value__isnull", True),
                        ("decimal_value__isnull", True),
                        ("option__isnull", False),
                        ("text_value__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cf_exactly_one_typed_value",
            ),
        ),
    ]
