// Removing native choice controls/localization must break this real editor test.
import { build } from 'esbuild';
import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
const root = process.env.SOURCE_ROOT;
const { nativeUIBuild } = await import(root + '/deployments/audax/native-ui-test-build.mjs');
const result = await build(nativeUIBuild(root, process.cwd(), 'native-custom-fields-fixture.tsx'));
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH, headless: true, args: ['--no-sandbox'] });
try {
  const page = await browser.newPage();
  await page.setContent('<div id="root"></div>');
  await page.addScriptTag({ content: result.outputFiles[0].text });
  const currency = page.getByTestId('custom-field-currency');
  await currency.getByLabel('currency', { exact: true }).fill('1.234,56');
  assert.equal(await currency.getByRole('button', { name: 'Salvar', exact: true }).count(), 1, 'editor actions must be translated');
  await currency.getByRole('button', { name: 'Salvar', exact: true }).click();
  await currency.getByRole('alert').waitFor();
  assert.equal(await currency.getByLabel('currency', { exact: true }).inputValue(), '1.234,56');
  const checkbox = page.getByTestId('custom-field-checkbox');
  assert.equal(await checkbox.locator('select').count(), 0, 'use Plane popover choices, not browser-native select');
  await checkbox.getByRole('button', { name: 'checkbox', exact: true }).click();
  await page.getByRole('option', { name: 'Não', exact: true }).click();
  await checkbox.getByRole('button', { name: 'Salvar', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('result').textContent === 'false');
  await checkbox.getByRole('button', { name: 'checkbox', exact: true }).click();
  await page.getByRole('option', { name: 'Não definido', exact: true }).click();
  await checkbox.getByRole('button', { name: 'Salvar', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('result').textContent === 'null');
  await page.getByLabel('Nome do campo', { exact: true }).first().fill('Valor da oportunidade');
  await page.getByRole('button', { name: 'Tipo do campo', exact: true }).click();
  await page.getByRole('option', { name: 'Moeda (BRL)', exact: true }).click();
  await page.getByRole('button', { name: 'Criar campo', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('result').textContent.startsWith('{'));
  assert.deepEqual(JSON.parse(await page.locator('#result').textContent()), { name: 'Valor da oportunidade', type: 'currency' });
  const option = page.getByLabel('Nova opção — Stage', { exact: true });
  await option.fill('Proposta');
  await page.getByRole('button', { name: 'Adicionar opção', exact: true }).click();
  await page.getByRole('alert').last().waitFor();
  assert.equal(await option.inputValue(), 'Proposta', 'failed option creation must preserve input');
  const form = page.getByTestId('create-form');
  await form.getByLabel('amount', { exact: true }).fill('1.234,56');
  await form.getByRole('button', { name: 'Criar item', exact: true }).click();
  assert.deepEqual(JSON.parse(await page.locator('#form-result').textContent()), { custom_values: { amount: '1234.56' } }, 'form mode submits typed values with the item, without per-field requests');
  assert.equal(await form.getByRole('button', { name: 'Salvar', exact: true }).count(), 0, 'form mode has only the item submit action');
  await page.locator('#form-result').evaluate((node) => { node.textContent = ''; });
  await form.getByLabel('amount', { exact: true }).fill('1,235');
  await form.getByRole('button', { name: 'Criar item', exact: true }).click();
  await form.getByRole('alert').waitFor();
  assert.equal(await page.locator('#form-result').textContent(), '', 'invalid currency precision must block item submission');
  await form.getByRole('button',{name:'Reiniciar formulário',exact:true}).click();
  await page.waitForFunction(() => document.getElementById('custom-field-amount-input').value === '', null, {timeout: 2000});
  assert.equal(await form.getByLabel('amount',{exact:true}).inputValue(), '', 'create-more/reset must clear the displayed draft along with the form value');
  const display = page.getByTestId('display-properties');
  assert.equal(await display.getByRole('button', {name:'amount', exact:true}).count(), 1, 'custom fields belong in the native Display property controls');
  await display.getByRole('button', {name:'amount', exact:true}).click();
  assert.equal(await page.locator('#selected-fields').textContent(), '["amount"]');
  assert.equal(await display.getByTestId('custom-property-amount').count(), 1, 'selected custom properties must render on the card');
  assert.equal(await display.getByTestId('custom-property-amount').textContent(), 'amount: R$\u00a01.234,56');
  await display.getByRole('button', {name:'amount', exact:true}).click();
  assert.equal(await page.locator('#selected-fields').textContent(), '[]');
  assert.equal(await display.getByTestId('custom-property-amount').count(), 0);
  const group = page.getByTestId('custom-group');
  assert.equal(await group.getByRole('button', {name:'stage', exact:true}).count(), 1, 'select fields should be selectable in native grouping');
  assert.equal(await group.getByRole('button', {name:'amount', exact:true}).count(), 0, 'currency must not be grouped into arbitrary-value buckets');
  await group.getByRole('button', {name:'qualified', exact:true}).click();
  await page.getByTestId('custom-sort').getByRole('button',{name:'amount — Decrescente',exact:true}).click();
  assert.deepEqual(JSON.parse(await page.locator('#custom-config').textContent()), {version:1,columns:[],conditions:[],metrics:[],group_by:{field_id:'qualified'},sort:{field_id:'amount',direction:'desc'}});
  console.log('Native Portuguese editors/settings: popover choices, BRL creation, false/unset and failed-save retention verified.');
} finally { await browser.close(); }
